### ISSUE TITLE
Add Negative Prompts support

### ISSUE THREAD

**Issue by chavinlo** [parlance-zz/g-diffuser-bot#58]
I have seen many webUIs have it, but as far as I know no bot, or frontend has implemented it yet. The closest thing I could find is: https://github.com/invoke-ai/InvokeAI/search?q=negative

**Comment by parlance-zz** [comment]
I haven't personally investigated this so I can't promise any kind of timeframe for it, but I will add it to the list and plan to include it.

Thank you.

**Comment by keturn** [comment]
It might get included upstream, there's an open PR for it: https://github.com/huggingface/diffusers/pull/549

**Comment by parlance-zz** [comment]
> It might get included upstream, there's an open PR for it: [huggingface/diffusers#549](https://github.com/huggingface/diffusers/pull/549)

Thanks for the heads up, will hold off for now.

**Comment by parlance-zz** [comment]
The integration of haffried's GRPC server means we get this mostly for free now, I will move it up the list as I do not need to change much to support it now.

**Comment by aaronsantiago** [comment]
+1 to negative prompt support

**Comment by parlance-zz** [comment]
![image](https://user-images.githubusercontent.com/12847512/197250419-d306041f-4a8e-4902-b0de-34aace9fe68b.png)
![image](https://user-images.githubusercontent.com/12847512/197250429-bc48b2b2-48cd-4d07-a0d9-5c37af152103.png)

**Comment by parlance-zz** [comment]
This is coming next, along with arbitrary weighting syntax.

**Comment by parlance-zz** [comment]
negative prompts are in, weight syntax is next but will be a separate issue
