### ISSUE TITLE
Default to "prompt" when typing after /dream

### ISSUE THREAD

**Issue by aaronsantiago** [parlance-zz/g-diffuser-bot#75]
This is common practice across the board and would greatly improve usability

**Comment by parlance-zz** [comment]
I was wondering if that was possible, I'm still learning all the "new" discord app command features.

I'll try to get this done quickly as it should be simple.

**Comment by parlance-zz** [comment]
fixed! but the issue is apparently that you can't have a default value for the prompt field, so the default prompt setting will now do nothing.

I think this way is ultimately better because the command is much easier to write by hand.
