### ISSUE TITLE
Bot ignoring defaults for some options

### ISSUE THREAD

**Issue by aaronsantiago** [parlance-zz/g-diffuser-bot#77]
The ones I've noticed is that it isn't respecting my default model name (tried to switch it to 1.5), nor is it respecting my default n (its always forcing it back to 1 when i don't pass in an n specifically)

It is respecting my change to the default sampler (k_euler_ancestral)

**Comment by parlance-zz** [comment]
replicated / confirmed,  fix incoming soon

**Comment by parlance-zz** [comment]
DEFAULT_SAMPLE_SETTINGS.n  applies to the CLI, but in the discord bot it uses DISCORD_BOT_SETTINGS.default_output_n instead just so you can have separate defaults for the discord bot and CLI if you want.

The model name in DEFAULT_SAMPLE_SETTINGS.model_name should be respected, however the discord bot does not load and make available every model in the models.yaml manifest, there is a setting in the config file: DISCORD_BOT_SETTINGS.model_list = ["stable-diffusion-v1-4", "stable-diffusion-v1-5"]
In order for a model to be usable from the discord bot the id matching the model.yaml file should be in this list. The reasoning was that you might want to download and try other models locally before making them available via discord.
