### ISSUE TITLE
Seed shown in message is incorrect for n > 1

### ISSUE THREAD

**Issue by aaronsantiago** [parlance-zz/g-diffuser-bot#79]
It seems to show the seed from the last image rather than the first one, so if you copy/paste the command the seeds increase.

EG if n = 5, and the seed = 0, then the message in the channel on completion will say that the seed was 4

**Comment by parlance-zz** [comment]
Thanks for finding this, fixed here: https://github.com/parlance-zz/g-diffuser-bot/commit/bf93bfe351d94eb89d3551dea1e0d8d11930479b
